### ISSUE TITLE
Need support for order timings

### ISSUE THREAD

**Issue by nabilrhman** [NerdCats/TaskCat#72] opened 2016-06-30 07:13 UTC
![6](https://cloud.githubusercontent.com/assets/16797266/16479805/71b38f1a-3ec4-11e6-9ba4-3a32eccf0f8f.jpg)

**Comment by thehoneymad** [comment] 2016-07-24 10:22
Duplicate of #15

**Closed by thehoneymad** 2016-07-24 10:22 UTC
Labels: duplicate
